# use the Python 3.6 language
language: python
python:
  - "3.6"

# install mdl for checking Markdown
before_install:
  - gem install mdl

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev --three

# perform testing:
# --> run the internal test suite with pytest
# --> lint the README documentation with mdl
script:
  - pipenv run pytest -s -v
  - mdl README.md
